language: node_js
install:
    - npm install -g gulp
    - npm install
    - git config --global user.email "jubjub@jubjubnest.net"
    - git config --global user.name "Travis CI Build"
    - git config --global push.default simple
node_js:
    - "iojs"
script:
    - gulp
    # '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && gulp upload-docs || true'
